from manim import *
import itertools
class RellenoCulturasScene(Scene):
    CONFIG={
        'paises': [
            'Colombia',
            'Perú',
            'Ecuador',
            'Brasil',
            'Venezuela',
            'Bolivia',
            'Chile',
            'Paraguay',
            'Uruguay',
            'Argentina',
            'Guyana',
            'Surinam',
            'Irán',
            'Irak',
            'Arabia Saudita',
            'Emiratos Árabes Unidos',
            'Kuwait',
            'Nigeria',
            'Libia',
            'Argelia',
            'Egipto',
            'Qatar',
            'China',
            'India',
            'Indonesia',
            'Malasia',
            'Tailandia',
            'Vietnam',
            'Japón',
            'Corea del Sur',
            'Taiwán',
            'Singapur',
            'Bangladesh',
            'Filipinas',
            'Australia',
            'Nueva Zelanda',
            'Estados Unidos',
            'Canadá',
            'México',
            'Guatemala',
            'Honduras',
            'El Salvador',
            'Nicaragua',
            'Costa Rica',
            'Panamá',
            'Cuba',
            'República Dominicana',
            'Haití',
            'Jamaica',
            'Belice',
            'España',
            'Portugal',
            'Francia',
            'Italia',
            'Alemania',
            'Reino Unido',
            'Rusia',
            'Turquía',
            'Polonia',
            'Ucrania',
            'Rumania',
            'Kazajistán',
            'Grecia',
            'Bulgaria',
            'Islandia',
            'Noruega',
            'Suecia',
            'Finlandia',
            'Dinamarca',
            'Suiza',
            'Austria',
            'Bélgica',
            'Países Bajos',
            'Luxemburgo',
            'Irlanda',
            'Croacia',
            'Serbia',
            'Eslovenia',
            'Bosnia y Herzegovina',
            'Macedonia del Norte',
            'Albania',
            'Montenegro',
            'Kosovo',
            'Eslovaquia',
            'República Checa',
            'Hungría',
            'Moldavia',
            'Lituania',
            'Letonia',
            'Estonia',
            'Georgia',
            'Armenia',
            'Azerbaiyán',
            'Chipre',
            'Malta',
            'Bielorrusia',
            'Andorra',
            'Liechtenstein',
            'San Marino',
            'Mónaco',
            'Ciudad del Vaticano',
            'Uzbekistán',
            'Turkmenistán',
            'Tayikistán',
            'Kirguistán',
            'Túnez',
            'Marruecos',
            'Sudáfrica',
            'Níger',
            'Mali',
            'Chad',
            'Angola',
            'Mozambique',
            'Zambia',
            'Zimbabue',
            'Sudán',
            'Etiopía',
            'Somalia',
            'Yibuti',
            'Kenia',
            'Tanzania',
            'Uganda',
            'Ruanda',
            'Burundi',
            'Camerún',
            'Nigeria',
            'Benín',
            'Togo',
            'Ghana',
            'Costa de Marfil',
            'Guinea',
            'Sierra Leona',
            'Liberia',
            'Guinea-Bisáu',
            'Senegal',
            'Gambia',
            'Guinea Ecuatorial',
            'Gabón',
            'Congo',
            'República Democrática del Congo',
            'Santo Tomé y Príncipe',
            'Cabo Verde',
            'Madagascar',
            'Mauricio',
            'Comoras',
            'Seychelles',
            'Islas Marshall',
            'Micronesia',
            'Palaos',
            'Tuvalu',
            'Nauru',
            'Islas Salomón',
            'Vanuatu',
            'Samoa',
            'Papúa Nueva Guinea',
            'Fiyi',
            'Tonga',
        ],
        'colors': [
            RED,
            WHITE,
            BLUE_C,
            GREEN,
            YELLOW,
            ORANGE,
        ]
    }
    def construct(self):
        colors= itertools.cycle(self.CONFIG['colors'])
        paises=VGroup()
        for pais in self.CONFIG['paises']:
            pais= Text(pais, stroke_width=1, stroke_opacity=1, stroke_color=BLACK)
            pais.set_color(next(colors))
            pais.set(width=np.random.random()+.5)
            pais.move_to(self.get_position(pais))
            paises.add(pais)
        self.play(
            LaggedStartMap(
                Write,
                paises,
                lag_ratio=0.1,
            ),
            run_time=2
        )
        self.wait(5)
    def get_position(self, pais):
        return np.array([
            np.random.uniform(-config['frame_width']/2+1, config['frame_width']/2-1),
            np.random.uniform(-config['frame_height']/2+1, config['frame_height']/2-1),
            0
        ])